apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networks.samplecrd.k8s1.io
spec:
  group: samplecrd.k8s1.io
  versions:
  - name: v1
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    # A schema is required
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
             cidr:
              type: string
             gateway:
              type: string
  names:
    kind: Network
    plural: networks
  scope: Namespaced
